#!/bin/bash

verbose=false
while getopts ":v:" opt; do
  case ${opt} in
    v ) verbose=true
      ;;
#    \? ) echo "Usage: cmd [-h] [-t]"
#      ;;
  esac
 shift
done

if [ -z "$1" ]; then
 current="_"
else
 current="$1"
fi

currentFile="./chainLinks/$current"

if ! [ -f $currentFile ]; then
 echo "no chain found at ./chainLinks"
 exit 1
fi

while [ -f "$currentFile" ]
do
 next=$(grep -Po '(?<=proof:)[A-Za-z0-9]+' $currentFile)
 if [ -z "$next" ]; then
  #current not yet solved?
  echo -e "\033[1;33m$current\033[0m"
  grep -Pzo '(?s)(?<=contents:).+(?=level:)' $currentFile
  echo -e "\033[1;33m________________________________\033[0m"
  exit 0
 else
  #solution exists for current
  if [ $verbose ] ; then
   ./verify "$currentFile"
  else
   ./verify "$currentFile" >> /dev/null
  fi

  if [ $? ] ; then
   #current file is valid
   echo -e "\033[1;32m$current\033[0m"
   grep -Pzo '(?s)(?<=contents:).+(?=level:)' $currentFile
   echo -e "\033[1;32m________________________________\033[0m"
   current=$next
   currentFile="./chainLinks/$current"
  else
   #current file is invalid
   echo -e "\033[1;31m$current\033[0m"
   grep -Pzo '(?s)(?<=contents:).+(?=level:)' $currentFile
   exit 1
  fi
fi
done


if [ -f "./chainLinks/pending/$current" ]; then
  #current not yet solved?
  echo -e "\033[1;33m$current\033[0m"
  grep -Pzo '(?s)(?<=contents:).+(?=level:)' "./chainLinks/pending/$current"
  echo -e "\033[1;33m________________________________\033[0m"

fi
