#!/bin/bash

#todo: cleanup any previous listeners

#write pid of process
echo -n "$$" > ./pid
#ensure pipe
[ -p ./in ] || mkfifo ./in

# stop if pid file has been altered
while [ -f ./pid ] && [ "$(cat ./pid)" = "$$" ]
do
 #listen and write requests to pipe
 netcat -l -p 17770 >> ./in
done
